### ISSUE TITLE
Hold Menu is transparent on iOS

### ISSUE THREAD

**Issue by skam22** [enesozturk/react-native-hold-menu#59]
**Describe the bug**
Background of menu is transparent on iOS.

**Expected behavior**
Expected background to be opaque (not able to see content behind menu)

**Actual behavior**
Menu is transparent, background is visible.

**Screenshots**
![IMG_1915](https://user-images.githubusercontent.com/50343717/152076523-c3651022-ed10-4a00-aee8-454c56866db0.jpeg)
![IMG_1916](https://user-images.githubusercontent.com/50343717/152076596-e8852597-754b-46cc-aa23-caee8c96db96.jpeg)

**Package versions**
 - React: 17.0.2
 - React Native: 0.66.4
 - React Native Reanimated: 2.3.1
 - React Native Hold Menu: sonnysantino/react-native-hold-menu#fix/expo-modules
 - Expo: >=44.0.0-0 <45.0.0

**Additional context**

same code works fine on android.

**Comment by enesozturk** [comment]
Hi @skam22, did you successfully install expo modules on your project? Hold Menu uses expo-blur as peer dependency and there might be something about that package. Otherwise, it's really weird if it's not run as expected on iOS. I generally got this on Android... lol.

**Comment by skam22** [comment]
I ended up just not using the hold menu package since it wasn’t working correctly.

**Comment by enesozturk** [comment]
Yeah, I got it now with a new project. Will check it later. Thanks for following up!

**Comment by hirbod** [comment]
@enesozturk did you manage to bypass the issue?

**Comment by enesozturk** [comment]
@hirbod, yeah I think it's related to dependencies, expo-blur is not installed properly when install the hold menu. I think it's fixed, will release a new version soon.

**Comment by NikolaiMadlener** [comment]
Any updates on this? Have the same issue

**Comment by delyethan** [comment]
Temporary fix

```diff
diff --git a/node_modules/react-native-hold-menu/src/components/backdrop/Backdrop.tsx b/node_modules/react-native-hold-menu/src/components/backdrop/Backdrop.tsx
index 72e7d33..7cc1a5a 100644
--- a/node_modules/react-native-hold-menu/src/components/backdrop/Backdrop.tsx
+++ b/node_modules/react-native-hold-menu/src/components/backdrop/Backdrop.tsx
@@ -1,8 +1,10 @@
 import React, { memo } from 'react';
 import { StyleSheet } from 'react-native';
 import Animated, {
+  runOnJS,
   useAnimatedGestureHandler,
   useAnimatedStyle,
+  useDerivedValue,
   withDelay,
   withTiming,
 } from 'react-native-reanimated';
@@ -38,6 +40,11 @@ type Context = {
 
 const BackdropComponent = () => {
   const { state, theme } = useInternal();
+  const [firstTime, setFirstTime] = React.useState(false)
+  
+  useDerivedValue(() => {
+    if (!firstTime) runOnJS(setFirstTime)(state.value === CONTEXT_MENU_STATE.ACTIVE);
+  }, [state.value]);
 
   const tapGestureEvent = useAnimatedGestureHandler<
     TapGestureHandlerGestureEvent,
@@ -102,7 +109,7 @@ const BackdropComponent = () => {
       onGestureEvent={tapGestureEvent}
       onHandlerStateChange={tapGestureEvent}
     >
-      <AnimatedBlurView
+      {firstTime ? <AnimatedBlurView
         // @ts-ignore
         intensity={100}
         tint="default"
@@ -114,7 +121,7 @@ const BackdropComponent = () => {
             animatedInnerContainerStyle,
           ]}
         />
-      </AnimatedBlurView>
+      </AnimatedBlurView> : <Animated.View/>}
     </TapGestureHandler>
   );
 };
```

**Comment by enesozturk** [comment]
This should be fixed by the new release. Changes were made in the last PR (https://github.com/enesozturk/react-native-hold-menu/pull/73). I'll publish it soon. Thanks, guys!

**Comment by jadbarakat** [comment]
Hi @enesozturk - I am still facing this same issue today. Sorry, not sure if I was supposed to create a new issue but I found this and thought I'd tag onto it since it's the same issue, even though it's closed.

**Describe the bug**
Background of menu is transparent on iOS.

**Expected behavior**
Expected background to be opaque (not able to see content behind menu)

**Actual behavior**
Menu is transparent, background is visible.

**Screenshots**
![IMG_2BEB220B19A9-1](https://github.com/enesozturk/react-native-hold-menu/assets/68382811/bcc4f6ad-779a-44b9-974e-da6c73b889a1)

**Package versions**

React: 18.2.0
React Native: 0.71.8
React Native Reanimated: ~2.14.4
React Native Hold Menu: ^0.1.6
Expo: ~48.0.15

**Comment by jadbarakat** [comment]
OK mate never mind - I figured the problem out. My expo-blur version was 12.30.0 and apparently incompatible with my version of expo. Downgraded to 12.2.2 and it worked perfectly. Sorry for any inconvenience 🙂

**Comment by desfero** [comment]
Can confirm what @jadbarakat is saying, downgrading to `12.2.2` worked for me.
